#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2019, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#


#
# Catching up from notes
# http://wfau.metagrid.co.uk/code/firethorn/file/tip/doc/notes/stv/

# -----------------------------------------------------
# Swap to the branch and update.
#[user@desktop]

    source "${HOME}/firethorn.settings"
    pushd  "${FIRETHORN_CODE}"

        hg pull
        hg update
        hg update 2.1.28-tap-issues


    popd

# -----------------------------------------------------
# Read though the notes and logs.
#[user@desktop]

    source "${HOME}/firethorn.settings"
    notepath=${FIRETHORN_CODE}/doc/notes/stv/

    ---- ----

TODO
20180725-Gworewia-Issues.txt
20180725-Ramses-Databases.txt
20180803-Gworewia-Debugging.txt
20180806-TAP-Debugging.txt
20180820-Gworewia-OSA-Resource-setup.txt
20180820-trop02-TAP-deploy.txt
20180825-OSA-GUI-trop02-deploy.txt
20180829-OSA-GUI-trop02-deploy.txt
20180903-Taplint-TAP-Results.txt
20180904-OSA-GUI-trop02-deploy.txt
20180907-Genius-trop02-deploy.txt
20180912-OSA-Setup-Errors.txt
20181016-Disk-Space-Issues.txt
20181031-TAP-Ulov-deploy.txt
20181103-Validation-Utils-osa.txt
20181103-Validation-Utils-vsa.txt
20181103-Validation-Utils-wsa.txt
20181104-TAP-Validator.txt
20181130-BestDRx-Region-Table-Issues.txt
20181130-TAP-Issues.txt
20181207-Firethorn-System-Checker.txt
20181212-TAP-deploy.txt

    ---- ----
    gedit ${notepath}/20190201-Firethorn-System-Validator.txt

            Notes on running validator

            Set some environment variables.
            Download the compose YML file.
            YML file has one container, firethorn/firethorn-utils.
            YML file command is [bash].
            YML file passes env params to the container.

            Manually run the Python validator

                python3 -c "import firethorn_utils.validator as validator; validator.main()" -ft=${firethorn_base:?} -from=${from_email:?} -to=${to_email:?} -r=${resourceid:?} -u=${ft_user:?} -p=${ft_pass:?} -g=${ft_group:?} -v=True


    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing-All-Tables-Test-Results.txt

        Lots of data .. not much information.
        Makes sense if you know what the data is.

    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing-All-Tables-Test.txt

        Test metadata describes what was being tested :-)

            ## Date: 10 Feb 2019
            ## Firethorn Version: 2.1.28
            ## Resource ID: 1808
            ## VM: Cadelicia
            ## Server: trop01
            ## VM Version: 4.18.13-200.fc28.x86_64
            ## VM Platform: Fedora release 28 (Twenty Eight)
            ## User Database: FirethornUserdataZRQ20170621151245DEV

        Starting to see some exceptions, but we only have the Python errors not the server errors.

    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing-TAP-async-results.txt

        No test metadata :-(

            First time we see errors for BestDR1 data

                BestDR1.SpecObjAll          invalid literal for int() with base 10:
                BestDR1.Frame               invalid literal for int() with base 10:
                BestDR1.PlateX              invalid literal for int() with base 10:
                BestDR1.SDSSConstants       invalid literal for int() with base 10:

    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing-TAP-async.txt

        Test metadata describes what was being tested :-)

            ## Date: 10 Feb 2019
            ## Firethorn Version: 2.1.28
            ## Resource ID: 1808
            ## VM: Cadelicia
            ## Server: trop01
            ## VM Version: 4.18.13-200.fc28.x86_64
            ## VM Platform: Fedora release 28 (Twenty Eight)
            ## User Database: FirethornUserdataZRQ20170621151245DEV

            ## TEST 1
            ## Go through all tables of a resource and run an asynchronous TAP query
            ## Firethorn Utils can be used as described here:
            ## http://wfau.metagrid.co.uk/code/firethorn/file/fa50d2cbcfdd/doc/notes/stv/20190201-Firethorn-System-Validator.txt
            ## Test run on local machine, with a proxy connection to Cadelicia ("8080:8081")

        Test itself is buried in the command line

            /usr/bin/python3 -c "import firethorn_utils.tap_validator as validator;validator.main()" -ft=http://localhost:8081/firethorn -r=1808 -u=Soopheef1AeKeeyohtos -p=Faew3yoohuechoo8eiT6 -g=iuquae2poG8yiph7agh3 -v=True -m=async

        Test metadata doesn't say what the target table metadata contains.

            Is this testing against the metadata in the WFAU github repo ?
            What version of the metadata ?
            Were all of the catalogs loaded ?

            Is this the only clue '-r=1808' as to what resource was tested ?

                ## Resource ID: 1808

        Three tests run
            Testing [BestDR1.SpecObjAll] - FAIL
                huge stack trace from the Python client for a well known server error
                    ValueError: invalid literal for int() with base 10:

            Testing [BestDR1.TilingInfo] - PASS

            Testing [BestDR1.StripeDefs] - FAIL

                Testing stop here
                Details of the [BestDR1.StripeDefs] follow.

                This looks like the race condition issue.
                OGSA-DAI log shows COMPLETED callback was made.
                Firethorn job history shows COMPLETED callback was received.
                Firethorn result status shows COMPLETED.
                Firethorn job status shows RUNNING.

                Notes highlight an InvalidStateTransitionException

                    2019-02-10 20:37:05,930 DEBUG [FireThornTaskExecutor-53] [BlueTaskEntity]   state [COMPLETED][RUNNING]
                    2019-02-10 20:37:05,930 ERROR [FireThornTaskExecutor-53] [BlueTaskEntity] InvalidStateTransitionException [8080048]


    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing-TAP-sync-results.txt

        Test metadata describes what was being tested :-)

            ## Date: 10 Feb 2019
            ## Firethorn Version: 2.1.28
            ## Resource ID: 1808
            ## VM: Cadelicia
            ## Server: trop01
            ## VM Version: 4.18.13-200.fc28.x86_64
            ## VM Platform: Fedora release 28 (Twenty Eight)
            ## User Database: FirethornUserdataZRQ20170621151245DEV

            ## TEST 1
            ## Go through all tables of a resource and run a synchronous TAP query
            ## Firethorn Utils can be used as described here:
            ## http://wfau.metagrid.co.uk/code/firethorn/file/fa50d2cbcfdd/doc/notes/stv/20190201-Firethorn-System-Validator.txt
            ## Test run on local machine, with a proxy connection to Cadelicia ("8080:8081")

        Test itself is buried in the command line

            /usr/bin/python3 -c "import firethorn_utils.tap_validator as validator;validator.main()" -ft=http://localhost:8081/firethorn  -r=1808 -u=Soopheef1AeKeeyohtos -p=Faew3yoohuechoo8eiT6 -g=iuquae2poG8yiph7agh3 -v=True -m=sync

        Test metadata doesn't say what the target table metadata contains.

            Is this testing against the metadata in the WFAU github repo ?
            What version of the metadata ?
            Were all of the catalogs loaded ?

            Is this the only clue '-r=1808' as to what resource was tested ?

                ## Resource ID: 1808

        Lots of different errors in a BLOB of JSON.
        Missing is a clear list of the errors.

            VHSDR2.MultiframeDetector           ValueError: invalid literal for int() with base 10
            VIDEODR5.FilterSections             ValueError: invalid literal for int() with base 10
            IRAS.iras_asc                       ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXDetection          HTTP Error 400
            BestDR5.SpecObj                     ValueError: invalid literal for int() with base 10
            BestDR7.\"Region\"                  ValueError: invalid literal for int() with base 10
            BestDR1.PlateX                      ValueError: invalid literal for int() with base 10
            BestDR7.SpecObj                     ValueError: invalid literal for int() with base 10
            VVVDR4.ExternalProductCatalogue     HTTP Error 400
            BestDR8.Frame                       ValueError: invalid literal for int() with base 10
            BestDR9.Frame                       ValueError: invalid literal for int() with base 10
            BestDR9.SpecObj                     ValueError: invalid literal for int() with base 10
            VVVDR4.CurationTask                 HTTP Error 400
            VVVDR4.vvvSource                    HTTP Error 400
            BestDR1.Frame                       ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXiras_psc           HTTP Error 400
            VIKINGDR2.vikingTilePawTDOnly       ValueError: invalid literal for int() with base 10
            BestDR9.segue1SpecObjAll            ValueError: invalid literal for int() with base 10
            BestDR9.segueSpecObjAll             ValueError: invalid literal for int() with base 10
            VVVDR4.Survey                       HTTP Error 400
            VVVDR4.Provenance                   HTTP Error 400
            VIDEODR2.CurrentAstrometry          ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXtwomass_xsc        HTTP Error 400
            VVVDR4.RequiredStack                HTTP Error 400
            ROSAT.rosat_fsc                     E04: Invalid bit value 'true'
            VVVDR4.vvvSourceExtinction          HTTP Error 400
            VVVDR4.SurveyProgrammes             HTTP Error 400
            BestDR3.PlateX                      ValueError: invalid literal for int() with base 10
            VIDEODR4.CurrentAstrometry          ValueError: invalid literal for int() with base 10
            VVVDR4.Programme                    HTTP Error 400
            VMCDR1.MultiframeDetectorEsoKeys    ValueError: invalid literal for int() with base 10
            BestDR3.SiteDBs                     HTTP Error 400
            BestDR9.StarTag                     <urlopen error timed out>
            BestDR9.\"Region\"                  ValueError: invalid literal for int() with base 10
            VVVDR4.vvvDetection                 HTTP Error 400
            BestDR9.SpecObjAll                  ValueError: invalid literal for int() with base 10
            IRAS.iras_psc                       E04: Invalid bit value 'false'
            BestDR5.QsoConcordance              E04: Invalid bit value 'true'
            VVVDR4.vvvTilePawPrints             HTTP Error 400
            VVVDR4.vvvVarFrameSetInfo           HTTP Error 400
            UKIDSSDR5PLUS.MultiframeDetector    ValueError: invalid literal for int() with base 10
            VVVDR4.ProgrammeTable               HTTP Error 400
            VVVDR4.vvvSourceXSynopticSource     HTTP Error 400
            BestDR5.QsoCatalog                  E04: Invalid bit value 'true'
            VIDEODR3.MultiframeDetectorEsoKeys  ValueError: invalid literal for int() with base 10
            BestDR1.SpecObjAll                  ValueError: invalid literal for int() with base 10
            VIKINGDR3.MultiframeDetector        ValueError: invalid literal for int() with base 10
            BestDR8.\"Region\"                  ValueError: invalid literal for int() with base 10
            BestDR7.QsoCatalog                  E04: Invalid bit value 'true'
            TWOMASS.twomass_sixx2_psc           <urlopen error timed out>
            BestDR5.PhotoProfile                ValueError: invalid literal for int() with base 10
            VVVDR4.Release                      HTTP Error 400
            VVVDR4.vvvMergeLog                  HTTP Error 400
            VVVDR4.ExternalProduct              <urlopen error timed out>
            VVVDR4.Filter                       HTTP Error 400
            VVVDR4.ExternalSurvey               <urlopen error timed out>
            VVVDR4.vvvSourceXxmm3dr4            HTTP Error 400
            BestDR3.PhotoProfile                ValueError: invalid literal for int() with base 10
            BestDR9.Sky                         <urlopen error timed out>
            VVVDR4.vvvSynopticSource            HTTP Error 400
            VVVDR4.MultiframeEsoKeys            HTTP Error 400
            BestDR3.SpecObjAll                  ValueError: invalid literal for int() with base 10
            VVVDR4.ProductLinks                 HTTP Error 400
            VIDEODR3.CurrentAstrometry          ValueError: invalid literal for int() with base 10
            BestDR9.segue2SpecObjAll            ValueError: invalid literal for int() with base 10
            VMCDR1.CurrentAstrometry            ValueError: invalid literal for int() with base 10
            VMCDR2.MultiframeEsoKeys            ValueError: invalid literal for int() with base 10
            BestDR8.SiteDiagnostics             <urlopen error timed out>",
            VVVDR4.ExternalSurveyTable          HTTP Error 400
            VVVDR4.vvvSourceXglimpse1_hrc       HTTP Error 400
            VIDEODR3.videoTilePawTDOnly         ValueError: invalid literal for int() with base 10
            BestDR3.SpecObj                     ValueError: invalid literal for int() with base 10
            Stripe82.PhotoObjAll                ValueError: invalid literal for int() with base 10
            BestDR5.SpecObjAll                  ValueError: invalid literal for int() with base 10
            VIDEODR2.videoTilePawPrints         ValueError: invalid literal for int() with base 10
            VIDEODR3.MultiframeDetector         ValueError: invalid literal for int() with base 10
            BestDR5.QsoCatalogAll               Invalid bit value 'true'
            VVVDR4.ProgrammeFrame               HTTP Error 400
            VMCDR3.CurrentAstrometry            ValueError: invalid literal for int() with base 10
            BestDR8.SDSSConstants               <urlopen error timed out>
            VVVDR4.SectionDetectors             HTTP Error 400
            VIDEODR3.videoTilePawPrints         ValueError: invalid literal for int() with base 10
            VHSDR3.FilterSections               ValueError: invalid literal for int() with base 10
            VHSDR1.MultiframeEsoKeys            ValueError: invalid literal for int() with base 10
            VMCDR3.FilterSections               ValueError: invalid literal for int() with base 10
            BestDR8.Sky                         <urlopen error timed out>
            VVVDR4.FilterSections               HTTP Error 400
            BestDR5.Frame                       ValueError: invalid literal for int() with base 10
            BestDR3.Frame                       ValueError: invalid literal for int() with base 10
            BestDR5.QsoTarget                   Invalid bit value 'false'
            VVVDR4.vvvSourceXwise_allskysc      HTTP Error 400
            VIDEODR4.MultiframeDetectorEsoKeys  ValueError: invalid literal for int() with base 10
            VMCDR4.CurrentAstrometry            ValueError: invalid literal for int() with base 10
            VHSDR2.CurrentAstrometry            ValueError: invalid literal for int() with base 10
            VMCDR4.MultiframeDetector           ValueError: invalid literal for int() with base 10
            BestDR7.Unknown                     <urlopen error timed out>
            VMCDR2.MultiframeDetector           ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXDR8gpsSource       HTTP Error 400
            BestDR7.QsoConcordance              Invalid bit value 'true'
            VMCDR4.FilterSections               ValueError: invalid literal for int() with base 10
            VIKINGDR2.vikingTilePawPrints       ValueError: invalid literal for int() with base 10
            VVVDR4.RequiredMosaic               HTTP Error 400
            VVVDR4.vvvSourceXSSASource          HTTP Error 400
            VVVDR4.MultiframeDetector           HTTP Error 400
            BestDR7.QsoConcordanceAll           Invalid bit value 'true'
            VVVDR4.vvvSynopticMergeLog          HTTP Error 400
            BestDR7.PlateX                      ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXglimpse2_mca       HTTP Error 400
            BestDR7.Frame                       ValueError: invalid literal for int() with base 10
            VVVDR4.vvvVariability               HTTP Error 400
            VIDEODR2.videoTilePawTDOnly         ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXglimpse2_hrc       HTTP Error 400
            VVVDR4.vvvTilePawTDOnly             HTTP Error 400
            BestDR8.SpecObj                     ValueError: invalid literal for int() with base 10
            BestDR8.segueSpecObjAll             ValueError: invalid literal for int() with base 10
            VVVDR4.AstrCalVers                  HTTP Error 400
            VVVDR4.RequiredMergeLogMultiEpoch   HTTP Error 400
            VMCDR3.MultiframeDetector           ValueError: invalid literal for int() with base 10
            VVVDR4.RequiredNeighbours           HTTP Error 400
            UKIDSSDR5PLUS.RequiredMosaic        ValueError: invalid literal for int() with base 10
            VIDEODR4.FilterSections             ValueError: invalid literal for int() with base 10
            VVVDR4.RequiredDiffImage            HTTP Error 400
            VVVDR4.PreviousMFDZP                HTTP Error 400
            VIKINGDR4.MultiframeDetectorEsoKeys ValueError: invalid literal for int() with base 10
            VVVDR4.ArchiveCurationHistory       HTTP Error 400
            VHSDR3.MultiframeDetectorEsoKeys    ValueError: invalid literal for int() with base 10
            VIKINGDR4.FilterSections            ValueError: invalid literal for int() with base 10
            UKIDSSDR6PLUS.RequiredMosaic        ValueError: invalid literal for int() with base 10
            VHSDR1.vhsTilePawPrints             ValueError: invalid literal for int() with base 10
            BestDR5.PlateX                      ValueError: invalid literal for int() with base 10
            BestDR7.QsoTarget                   Invalid bit value 'false'
            VVVDR4.vvvSourceXDetectionBestMatch HTTP Error 400
            VVVDR4.Multiframe                   HTTP Error 400
            VVVDR4.PhotCalVers                  HTTP Error 400
            BestDR8.segue1SpecObjAll            ValueError: invalid literal for int() with base 10
            VHSDR2.vhsTilePawPrints             ValueError: invalid literal for int() with base 10
            UKIDSSDR4PLUS.RequiredMosaic        ValueError: invalid literal for int() with base 10
            BestDR8.TwoMass                     <urlopen error timed out>
            VVVDR4.vvvAstrometricInfo           HTTP Error 400
            VVVDR4.EpochFrameStatus             HTTP Error 400
            ROSAT.rosat_bsc                     ValueError: invalid literal for int() with base 10
            BestDR5.QsoConcordanceAll           Invalid bit value 'true'
            VVVDR4.ProgrammeCurationHistory     HTTP Error 400
            VMCDR4.MultiframeDetectorEsoKeys    ValueError: invalid literal for int() with base 10
            BestDR8.SpecObjAll                  <urlopen error timed out>
            VVVDR4.MultiframeDetectorEsoKeys    HTTP Error 400
            BestDR7.SpecObjAll                  ValueError: invalid literal for int() with base 10
            VVVDR4.vvvSourceXglimpse1_mca       HTTP Error 400
            VVVDR4.vvvSourceXtwomass_psc        HTTP Error 400
            VVVDR4.RequiredTile                 HTTP Error 400
            VIDEODR2.MultiframeDetector         ValueError: invalid literal for int() with base 10
            BestDR7.QsoCatalogAll               Invalid bit value 'true'
            BestDR8.segue2SpecObjAll            ValueError: invalid literal for int() with base 10
            BestDR9.PhotoProfile                <urlopen error timed out>",
            WISE.wise_prelimsc                  ValueError: invalid literal for int() with base 10
            BestDR9.neighbors                   <urlopen error timed out>",
            VVVDR4.vvvTileSet                   HTTP Error 400
            VVVDR4.CurrentAstrometry            HTTP Error 400
            VVVDR4.RequiredFilters              HTTP Error 400
            VMCDR2.MultiframeDetectorEsoKeys    ValueError: invalid literal for int() with base 10
            BestDR8.USNO                        ValueError: invalid literal for int() with base 10

        Same set or errors reoccur

            ValueError: invalid literal
            Invalid bit value
            HTTP Error 400
            <urlopen error timed out>

        So far no diagnosis about _why_ we are getting these errors.

            ....

    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing-TAP-sync.txt

        Test metadata describes what was being tested :-)

            ## Date: 10 Feb 2019
            ## Firethorn Version: 2.1.28
            ## Resource ID: 1808
            ## VM: Cadelicia
            ## Server: trop01
            ## VM Version: 4.18.13-200.fc28.x86_64
            ## VM Platform: Fedora release 28 (Twenty Eight)
            ## User Database: FirethornUserdataZRQ20170621151245DEV

            ## TEST 1
            ## Go through all tables of a resource and run a synchronous TAP query
            ## Firethorn Utils can be used as described here:
            ## http://wfau.metagrid.co.uk/code/firethorn/file/fa50d2cbcfdd/doc/notes/stv/20190201-Firethorn-System-Validator.txt

        Test itself is buried in the command line

            /usr/bin/python3 -c "import firethorn_utils.tap_validator as validator;validator.main()" -ft=http://localhost:8081/firethorn -r=1808 -u=Soopheef1AeKeeyohtos -p=Faew3yoohuechoo8eiT6 -g=iuquae2poG8yiph7agh3 -v=True -m=sync

        Test metadata doesn't say what the target table metadata contains.

            Is this testing against the metadata in the WFAU github repo ?
            What version of the metadata ?
            Were all of the catalogs loaded ?

            Is this the only clue '-r=1808' as to what resource was tested ?

                ## Resource ID: 1808

        Comment suggests same test as before, but no errors !?

            ## Queries seem to be working fine, no query hangs so far
            ## Will update once test has completed

        No update ....

    ---- ----
    gedit ${notepath}/20190210-Firethorn-Testing.txt

        Notes on issues found so far ..

            # Issues found during testing
            # Todo: Create Redmine issues with details

            - TAP Async Test (All Tables):

              - Query hanging
                  Investigating shows that result state does not match query status

              - Astropy Error while reading VOTable response
                  "ValueError: invalid literal for int() with base 10:"
                   .. Query returns an "img" field which has type unsignedByte in the VOTable
                   .. Astropy tries to read this as an integer and fails
                    https://msdn.microsoft.com/en-us/library/ee625175(v=exchg.80).aspx
	            "The unsignedByte data type is an integer value between 0 and 255, inclusive."

            - TAP Sync Test (All Tables):
              - Same Astropy Error mentioned above

            Firethorn Query Test (All Tables):
              - Bad Status Line Exceptions

        ----

        Questions about these

            Query hanging

                No detail on how to reproduce this yet.

            Astropy ValueError

                What is the actual data in the database ?

                What _should_ we return as the VOTable data type  ?

                Are we returning the wrong type, or is Astropy unable to handle 'unsignedByte' ?

                Have we reported this to Astropy ?
                Have we suggested a fix to Astropy ?

            Bad Status Line

                What does this mean ?

        ----

        Issues not discussed

            What is causing the "Invalid bit value" errors ?

            What is causing the "HTTP Error 400" responses ?

            What is causing the "urlopen error timed out" ?

        ----

        More questions than answers at this point


    ---- ----
    gedit ${notepath}/20190210-OSA-TAP-debug.txt

        Virtual machines failing

            [Acilamwen]

                Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

            [Ibalehar]

                Filesystem      Size  Used Avail Use% Mounted on
                ....
                /dev/vda3        15G  6.7G  6.6G  51% /

            [Eterathiel]

                Filesystem      Size  Used Avail Use% Mounted on
                ....
                /dev/vda3        15G  4.2G  8.9G  33% /

            [Lothigometh]

                Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

            [Siamond]

                Host key verification failed.

            Name [Araybwyn]

                ssh: connect to host araybwyn port 22: No route to host

        Concentrating on the firethorn VM, Araybwyn.

            No route to host

            Rebooted via virsh.

            Still no access

            Possible issues with memory ?

                virsh dominfo

                    ....
	                Max memory:     4194304 KiB
	                Used memory:    4194304 KiB
                    ....

            Needs a stronger reboot

                virsh reboot doesn't reboot

                virsh destroy
                virsh start

            Disc looks fine

                Filesystem      Size  Used Avail Use% Mounted on
                ....
                /dev/vda3        31G   17G   14G  56% /

            Restart servicesusing 'compose run'


        Good notes on devbugging Apache logs

            ## Need to check why health checker cron job on my machine did not catch TAP service unresponsiveness
            ## UPDATE (11/Feb/2019): Health Checker should now be fixed. Is set to run every 45mins

            ## Let's check the Apache proxy logs the day the VM crashed (February 4th 2019)

            ## Results can be found in 20190211-OSA-TAP-debug-Apache-Logs.txt

            ## VM seems to die around 04/Feb/2019:13:05:17
            ## There is a validator running queries on the TAP service just before it does

                195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 201 1335 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "GET /firethorn/adql/table/26612169 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "POST /firethorn/blue/query/26607251 HTTP/1.1" 200 1976 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/adql/table/26612169 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/blue/query/26607251 HTTP/1.1" 200 2929 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/blue/query/26607251 HTTP/1.1" 200 2929 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 201 12641 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/adql/table/26612173 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
                195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
                178.79.157.93 - - [04/Feb/2019:14:00:01 +0000] "GET /osa/availability HTTP/1.1" 503 299 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
                195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "POST /firethorn/blue/query/26613652 HTTP/1.1" 502 438 "-" "Python-urllib/3.4"

                Odd use of words 'a validator running queries'
                The IP address is one of ours.

                    66.121.194.195.in-addr.arpa domain name pointer vpngate.roe.ac.uk.

                My guess is this is 'one of *our* validators running queries' .. ?

            ## GET request to /firethorn/adql/resource/56 is the last successful request before crash
            ## Possible hints in the last few queries?

                ## http://tap.roe.ac.uk/firethorn/blue/query/26607246
                   SELECT TOP 10 * FROM BestDR9.GalaxyTag
                   - Completed Job
                   - VOTable with no rows (Table Deleted)
                   - A column with unsignedByte (This column type seems to be problematic, need to look into this)

                ## http://tap.roe.ac.uk/firethorn/blue/query/26607247
                   SELECT TOP 10 * FROM VVVDR4.Multiframe
                   - Completed Job
                   - VOTable with no rows (Table Deleted)
                   - A column with unsignedByte (This column type seems to be problematic, need to look into this)

                ## http://tap.roe.ac.uk/firethorn/blue/query/26607248
                   SELECT TOP 10 * FROM BestDR9.galSpecLine
                   - Completed Job
                   - VOTable with no rows (Table Deleted)

                ## http://tap.roe.ac.uk/firethorn/blue/query/26607249
                   SELECT TOP 10 * FROM VVVDR4.MultiframeDetector
                   - Completed Job
                   - VOTable with no rows (Table Deleted)
                   - A column with unsignedByte (This column type seems to be problematic, need to look into this)

                ## http://tap.roe.ac.uk/firethorn/blue/query/26607250
                   SELECT TOP 10 * FROM BestDR9.Run
                   - Completed Job
                   - VOTable with no rows (Table Deleted)
                   - A column with unsignedByte (This column type seems to be problematic, need to look into this)

                ## http://tap.roe.ac.uk/firethorn/blue/query/26607251
                   SELECT TOP 10 * FROM BestDR9.Segue2Target1
                   - Completed Job
                   - VOTable with no rows (Table Deleted)
                   - A column with unsignedByte (This column type seems to be problematic, need to look into this)

                ## http://tap.roe.ac.uk/firethorn/blue/query/26613652
                   SELECT TOP 10 * FROM VVVDR4.MultiframeDetectorEsoKeys
                   - status is "READY"
                   - Query never started?
                   -

                    "history": [
                        	{
		                    "type": "http://data.metagrid.co.uk/wfau/firethorn/types/log-entry-1.0.json",
		                    "level": "INFO",
		                    "task": "http://tap.roe.ac.uk/firethorn/blue/query/26613652",
		                    "message": "Executing query",
		                    "state": "READY",
		                    "owner": "http://tap.roe.ac.uk/firethorn/community-member/163",
		                    "url": "http://tap.roe.ac.uk/firethorn/blue/log/entry/26613606",
		                    "self": "http://tap.roe.ac.uk/firethorn/blue/log/entry/26613606",
		                    "ident": "26613606",
		                    "created": "2019-02-04T13:05:17.348",
		                    "modified": "2019-02-04T13:05:17.349"
		                    }
	                    ],

                ## Blue Query numbering seems strange.. Jumping from 26607251 which was the last completed query to 26613652 ?
                ## http://tap.roe.ac.uk/firethorn/blue/query/26613651 for example does not exist (26613652 - 1)

                ## Check the httpd error logs (/var/log/httpd/tap.roe.ac.uk-error.log)

                    [Mon Feb 04 14:00:20.094303 2019] [proxy:error] [pid 5522:tid 139756264474368] (113)No route to host:
                        AH00957: HTTP: attempt to connect to 192.168.202.8:8080 (*) failed
                    [Mon Feb 04 14:00:20.094393 2019] [proxy_http:error] [pid 5522:tid 139756264474368] [client 178.79.157.93:40936]
                        AH01114: HTTP: failed to make connection to backend: araybwyn
                    [Mon Feb 04 14:45:17.108362 2019] [proxy_http:error] [pid 5521:tid 139756549629696] (70007)The timeout specified has expired: [client 195.194.121.66:56730]
                        AH01102: error reading status line from remote server araybwyn:8080
                    [Mon Feb 04 14:45:17.108443 2019] [proxy:error] [pid 5521:tid 139756549629696] [client 195.194.121.66:56730]
                        AH00898: Error reading from remote server returned by /firethorn/blue/query/26613652
                    [Mon Feb 04 14:45:17.691333 2019] [proxy_http:error] [pid 5521:tid 139756532844288] (70007)The timeout specified has expired: [client 195.194.121.66:56736]
                        AH01102: error reading status line from remote server araybwyn:8080
                    [Mon Feb 04 14:45:17.691380 2019] [proxy:error] [pid 5521:tid 139756532844288] [client 195.194.121.66:56736]
                        AH00898: Error reading from remote server returned by /firethorn/adql/table/26612173
                    [Mon Feb 04 14:45:20.190543 2019] [proxy:error] [pid 5522:tid 139756423837440] (113)No route to host:
                        AH00957: HTTP: attempt to connect to 192.168.202.8:8080 (*) failed


    ---- ----
    gedit ${notepath}/20190211-Firethorn-Testing-Taplint-OSA.txt

        ## Date: 11 Feb 2019
        ## Test: Use TAPlint (stilts.jar) to validate live tap.roe.ac.uk/osa TAP service

            Section TMV: Validate table metadata against XML schema
            I-TMV-VURL-1 Validating http://tap.roe.ac.uk/osa/tables as tableset (http://www.ivoa.net/xml/VODataService/v1.1)
            S-TMV-VALI-1 SAX report: warnings 0, errors 0, fatal 0

            Section TME: Check content of tables metadata from /tables
            I-TME-TURL-1 Reading table metadata from http://tap.roe.ac.uk/osa/tables
            S-TME-SUMM-1 Schemas: 17, Tables: 737, Columns: 31445, Foreign Keys: 0
            S-TME-FLGS-1 Standard column flags: indexed: 0, primary: 0, nullable: 0
            S-TME-FLGO-1 Other column flags: none

            ....

            Section CPV: Validate capabilities against XML schema
            I-CPV-VURL-1 Validating http://tap.roe.ac.uk/osa/capabilities as capabilities (http://www.ivoa.net/xml/VOSICapabilities/v1.0)
            S-CPV-VALI-1 SAX report: warnings 0, errors 0, fatal 0

            Section CAP: Check content of TAPRegExt capabilities record
            I-CAP-CURL-1 Reading capability metadata from http://tap.roe.ac.uk/osa/capabilities

            Section AVV: Validate availability against XML schema
            I-AVV-VURL-1 Validating http://tap.roe.ac.uk/osa/availability as availability (http://www.ivoa.net/xml/VOSIAvailability/v1.0)
            S-AVV-VALI-1 SAX report: warnings 0, errors 0, fatal 0

            ....
            ....
            E-MDQ-QERR-1 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ArchiveCurationHistory [Service error: "null"]
            ....
            E-MDQ-QERR-2 Failed TAP query SELECT TOP 1 * FROM VVVDR4.AstrCalVers [Service error: "null"]
            ....
            E-MDQ-QERR-3 Failed TAP query SELECT TOP 1 * FROM VVVDR4.CurationTask [Service error: "null"]
            ....
            E-MDQ-QERR-4 Failed TAP query SELECT TOP 1 * FROM VVVDR4.CurrentAstrometry [Service error: "null"]
            ....
            E-MDQ-QERR-5 Failed TAP query SELECT TOP 1 * FROM VVVDR4.EpochFrameStatus [Service error: "null"]
            ....
            E-MDQ-QERR-6 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalProduct [Service error: "null"]
            ....
            E-MDQ-QERR-7 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalProductCatalogue [Service error: "null"]
            ....
            E-MDQ-QERR-8 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalSurvey [Service error: "null"]
            ....
            E-MDQ-QERR-9 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalSurveyTable [Service error: "null"]

        ## Manual Stop..
        ## VVVDR4 is missing from ramses19
        ## Queries are not completing

            If it is missing from ramses19, then how did it get into the metadata ?

    ---- ----
    gedit ${notepath}/20190211-Firethorn-Testing-Taplint.txt

        ## Date: 11 Feb 2019
        ## Firethorn Version: 2.1.28
        ## Resource ID: 1808
        ## VM: Cadelicia
        ## Server: trop01
        ## VM Version: 4.18.13-200.fc28.x86_64
        ## VM Platform: Fedora release 28 (Twenty Eight)
        ## User Database: FirethornUserdataZRQ20170621151245DEV
        ## localhost:8081 -> Cadelicia:8080

            Section TMV: Validate table metadata against XML schema
            ....

            Section TME: Check content of tables metadata from /tables
            ....

            Section TMS: Check content of tables metadata from TAP_SCHEMA
            ....

            Section TMC: Compare table metadata from /tables and TAP_SCHEMA
            ....

            Section CPV: Validate capabilities against XML schema
            ....

            Section CAP: Check content of TAPRegExt capabilities record
            ....

            Section AVV: Validate availability against XML schema
            ....

            Section QGE: Make ADQL queries in sync GET mode
            ....

            Section QPO: Make ADQL queries in sync POST mode
            ....

            Section QAS: Make ADQL queries in async mode
            ....

            Section UWS: Test asynchronous UWS/TAP behaviour
            ....

            Section MDQ: Check table query result columns against declared metadata
            I-MDQ-QSUB-1 Submitting query: SELECT TOP 1 * FROM "FIRST".first08Jul16Source
            I-MDQ-QSUB-2 Submitting query: SELECT TOP 1 * FROM "FIRST".firstSource
            I-MDQ-QSUB-3 Submitting query: SELECT TOP 1 * FROM "FIRST".firstSource12Feb16
            I-MDQ-QSUB-4 Submitting query: SELECT TOP 1 * FROM BestDR1."Diagnostics"
            I-MDQ-QSUB-5 Submitting query: SELECT TOP 1 * FROM BestDR1."First"
            I-MDQ-QSUB-6 Submitting query: SELECT TOP 1 * FROM BestDR1."Match"
            I-MDQ-QSUB-7 Submitting query: SELECT TOP 1 * FROM BestDR1."Region"
            I-MDQ-QSUB-8 Submitting query: SELECT TOP 1 * FROM BestDR1."Zone"
            I-MDQ-QSUB-9 Submitting query: SELECT TOP 1 * FROM BestDR1.Best2Sector
            E-MDQ-QERR-1 Failed TAP query SELECT TOP 1 * FROM BestDR3.SiteDBs [Service error: "null"]
            ....

        ## Hangs..

            E-MDQ-QERR-2 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ArchiveCurationHistory [Service error: "null"]
            ....
            E-MDQ-QERR-3 Failed TAP query SELECT TOP 1 * FROM VVVDR4.AstrCalVers [Service error: "null"]
            ....
            E-MDQ-QERR-4 Failed TAP query SELECT TOP 1 * FROM VVVDR4.CurationTask [Service error: "null"]
            ....
            E-MDQ-QERR-5 Failed TAP query SELECT TOP 1 * FROM VVVDR4.CurrentAstrometry [Service error: "null"]
            ....
            E-MDQ-QERR-6 Failed TAP query SELECT TOP 1 * FROM VVVDR4.EpochFrameStatus [Service error: "null"]
            ....
            E-MDQ-QERR-7 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalProduct [Service error: "null"]
            ....
            E-MDQ-QERR-8 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalProductCatalogue [Service error: "null"]
            ....
            E-MDQ-QERR-9 Failed TAP query SELECT TOP 1 * FROM VVVDR4.ExternalSurvey [Service error: "null"]
            ....

        ## Manual stop..
        ## It looks like these are running into timeouts

        ## SELECT TOP 1 * FROM BestDR3.SiteDBs
        ## Checking on Ramses19, it looks like BestDR3 is actually BESTDR3
        ## Need to update tap deployment metadata to match this

            If the catalog name isn't in quotes, then we shouldn't be case sensitive.

        ## VVVDR4 Does not exist on ramses19 which is the server being tested
        ## Check what one of the VVVDR4 Tables queries is doing
        ## i.e. http://localhost:8081/firethorn/blue/query/7913021

            If it is missing from ramses19, then how did it get into the metadata ?



        ## Looks like its stuck with a status of Running
        ## Results state is Completed though

            {
            ....
            "input": "SELECT TOP 5 * FROM BestDR1.HoleObj",
            ....
            "results": {
                "formats": {
                    "datatable": "http://localhost:8081/firethorn/adql/table/7914719/datatable",
                    "votable": "http://localhost:8081/firethorn/adql/table/7914719/votable"
                    },
                "count": 5,
                "state": "COMPLETED",
                "table": "http://localhost:8081/firethorn/adql/table/7914719"
                },
            ....
            "status": "RUNNING",
            ....
            "history": [
                    {
                    ....
                    "message": null,
                    "state": "COMPLETED",
                    ....
                    },
                    {
                    ....
                    "message": "Executing query",
                    "state": "READY",
                    ....
                    }
                ],
            ....
            "delays": {
                "every": null,
                "last": null,
                "first": null
                },
            "limits": {
                "cells": null,
                "rows": 1000000,
                "time": null
                },
            "syntax": {
                "friendly": null,
                "status": "VALID",
                "message": null
                },
            ....
            }

        Suspect this is a result of race condition ?
        Suspect taplint is using two stage async requests.
        The callback must have happened to set the result state to COMPLETED.
        Race condition means that callback COMPLETED is overwritten by update RUNNING.

    ---- ----
    gedit ${notepath}/20190211-Firethorn-Testing-VVVDR4-SDSSDR9-only.txt

        ## Date: 11 Feb 2019

        ## BestDR9 and VVVDR4 seem to appear in failing queries or just before VM crashes, so lets test just those
        ## Also VVVDR4 is currently not on ramses19 for some reason, so this is expected to fail, but lets see if it will crash the server or cause loop

        ## Modify firethorn-utils.validator to filter for those two only:

            ...
            for schema in  list(filter(lambda x: x.name().lower() in ["bestdr9", "vvvdr4"], resource.get_schemas())):
            ...

            /usr/bin/python3 -c "import firethorn_utils.validator as validator;validator.main()" -ft=http://localhost:8081/firethorn -r=1808 -u=Soopheef1AeKeeyohtos -p=Faew3yoohuechoo8eiT6 -g=iuquae2poG8yiph7agh3

                --- Starting validation on Resource: http://localhost:8081/firethorn/adql/resource/1808---
                Testing [BestDR9.SpecObjAll]
                Rowcount:10
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9658668

                ....
                ....
                ....
                ....

                Table query completed after 1.5893499851226807 seconds
                Testing [VVVDR4.vvvSourceXglimpse1_hrc]
                Rowcount:-1
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9684250

                Table query completed after 1.3341343402862549 seconds
                Testing [VVVDR4.vvvSourceXglimpse1_mca]

        ## Hangs Here..
        ## should note that I was simultaneously running a TAPlint validation, where queries on VVVDR4 where timeing out..

        ## ----------------------------------------------------------------------------------------------------------------

        ## Kill Test as well as concurrent Taplint Validation test and try this again, but only VVVDR4..

            /usr/bin/python3 -c "import firethorn_utils.validator as validator;validator.main()" -ft=http://localhost:8081/firethorn -r=1808 -u=Soopheef1AeKeeyohtos -p=Faew3yoohuechoo8eiT6 -g=iuquae2poG8yiph7agh3

                --- Starting validation on Resource: http://localhost:8081/firethorn/adql/resource/1808---
                Testing [VVVDR4.ArchiveCurationHistory]
                Rowcount:-1
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9689655
                Table query completed after 1.4808361530303955 seconds

                    ....
                    ....
                    ....
                    ....

                Testing [VVVDR4.Multiframe]
                Rowcount:-1
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9689666
                Table query completed after 2.3705923557281494 seconds

                Testing [VVVDR4.MultiframeDetector]

        ## Hangs..
        ## Looking at the Firethorn logs this query looks like its running:
        ## http://localhost:8081/firethorn/blue/query/9689667
        ## Check Job status
        ## status": "RUNNING",
        ## results -> state: "EMPTY",

            "history": [
	                {
	                ....
	                "message": "Executing query",
	                "state": "READY",
	                ....
	                }
	            ],

        ## Check OGSA-DAI Logs for clues:
        ## Last Output is an Exception for that query:

            2019-02-11 13:52:33,910 DEBUG event.LoggingActivityListener [pool-1-thread-3850,debug:84] uk.org.ogsadai.activity.sql.ActivitySQLUserException: The activity encountered a problem while interacting with a relational database.
	            at uk.ac.roe.wfau.firethorn.ogsadai.activity.server.sql.SQLQueryActivity.processIteration(SQLQueryActivity.java:322)
	            at uk.org.ogsadai.activity.MatchedIterativeActivity.process(MatchedIterativeActivity.java:90)
	            at uk.org.ogsadai.activity.event.EventfulActivity.process(EventfulActivity.java:78)
	            at uk.org.ogsadai.activity.concurrency.ActivityProcessingTask.call(ActivityProcessingTask.java:81)
	            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	            at java.lang.Thread.run(Thread.java:748)
            Caused by: java.sql.SQLException: Invalid object name 'VVVDR4.dbo.MultiframeDetector'.
	            at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	            at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2988)
	            at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2421)
	            at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:671)
	            at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQLQuery(JtdsStatement.java:505)
	            at net.sourceforge.jtds.jdbc.JtdsStatement.executeQuery(JtdsStatement.java:1427)
	            at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	            at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	            at uk.org.ogsadai.activity.sql.CallableStatement.call(CallableStatement.java:66)
	            at uk.ac.roe.wfau.firethorn.ogsadai.activity.server.sql.SQLQueryActivity$ChaoticCallableStatement.call(SQLQueryActivity.java:415)
	            at uk.ac.roe.wfau.firethorn.ogsadai.activity.server.sql.SQLQueryActivity$ChaoticCallableStatement.call(SQLQueryActivity.java:404)


        ## Hmm..Previous queries failed, but this one seems to be stuck in a RUNNING loop
        ## For some reason FAIL message was not propagated correctly here?

        ## Memory usage on Cadelicia shows 1.65GB/4GB used and swap is 415M/1024M

        ## ----------------------------------------------------------------------------------------------------------------

        ## Run same test a third time..

            /usr/bin/python3 -c "import firethorn_utils.validator as validator;validator.main()" -ft=http://localhost:8081/firethorn -r=1808 -u=Soopheef1AeKeeyohtos -p=Faew3yoohuechoo8eiT6 -g=iuquae2poG8yiph7agh3

                ....
                ....

                Testing [VVVDR4.ArchiveCurationHistory]
                Rowcount:-1
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9689668
                Table query completed after 1.5432765483856201 seconds

                ....
                ....
                ....
                ....
                ....
                ....
                ....
                ....

                Testing [VVVDR4.ProgrammeCurationHistory]
                Rowcount:-1
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9689687
                Table query completed after 1.4503490924835205 seconds

                Testing [VVVDR4.ProgrammeFrame]
                Rowcount:-1
                Query: None
                Query ID: http://localhost:8081/firethorn/blue/query/9689688
                Table query completed after 1.4523231983184814 seconds

                Testing [VVVDR4.ProgrammeTable]

        ## Hangs here..

        ## Basically every time test is run, it will hang at some Table query, which seems to be different everytime

    ---- ----

    Important thing .. need to modify the validator code to filter the targets.

        ## Modify firethorn-utils.validator to filter for those two only:

            ...
            for schema in  list(filter(lambda x: x.name().lower() in ["bestdr9", "vvvdr4"], resource.get_schemas())):
            ...

    ---- ----
    gedit ${notepath}/20190211-OSA-TAP-debug-Apache-Logs.txt

        Apache log that covers transition from normal operation to 503 proxy error.
        Ellipsis, '....', indicates one or more lines removed.
        Hline '--' highlights change in behaviour between consecutive lines.

            178.79.157.93 - - [03/Feb/2019:14:00:02 +0000] "GET /osa/availability HTTP/1.1" 200 224 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
            178.79.157.93 - - [03/Feb/2019:15:00:01 +0000] "GET /osa/availability HTTP/1.1" 200 224 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
            178.79.157.93 - - [03/Feb/2019:16:00:01 +0000] "GET /osa/availability HTTP/1.1" 200 224 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
            ....
            ....
            195.194.121.66 - - [04/Feb/2019:13:05:09 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 201 6944 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:09 +0000] "GET /firethorn/adql/table/26612167 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:09 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:10 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:10 +0000] "GET /firethorn/adql/table/26612167 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:09 +0000] "POST /firethorn/blue/query/26607249 HTTP/1.1" 200 7585 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:10 +0000] "GET /firethorn/adql/table/26612167 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:10 +0000] "GET /firethorn/blue/query/26607249 HTTP/1.1" 200 7585 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:10 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:11 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:11 +0000] "GET /firethorn/adql/table/26612167 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:11 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 201 2562 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:12 +0000] "POST /firethorn/blue/query/26607250 HTTP/1.1" 200 3203 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:12 +0000] "GET /firethorn/blue/query/26607250 HTTP/1.1" 200 4156 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:13 +0000] "GET /firethorn/blue/query/26607250 HTTP/1.1" 200 4156 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:13 +0000] "GET /firethorn/adql/table/26612171 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:13 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:13 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:13 +0000] "GET /firethorn/blue/query/26607249 HTTP/1.1" 200 9010 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/table/26612171 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/blue/query/26607249 HTTP/1.1" 200 9010 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/table/26612171 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/table/26612169 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:14 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "GET /firethorn/adql/table/26612171 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "GET /firethorn/adql/table/26612169 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 201 1335 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "GET /firethorn/adql/table/26612169 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:15 +0000] "POST /firethorn/blue/query/26607251 HTTP/1.1" 200 1976 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/adql/table/26612169 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/blue/query/26607251 HTTP/1.1" 200 2929 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/blue/query/26607251 HTTP/1.1" 200 2929 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 201 12641 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:16 +0000] "GET /firethorn/adql/table/26612173 HTTP/1.1" 200 1123 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/schema/548 HTTP/1.1" 200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            ----
            178.79.157.93  - - [04/Feb/2019:14:00:01 +0000] "GET /osa/availability HTTP/1.1" 503 299 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "POST /firethorn/blue/query/26613652 HTTP/1.1" 502 438 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/table/26612173 HTTP/1.1" 502 437 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:18 +0000] "GET /firethorn/adql/table/26612173 HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:17 +0000] "GET /firethorn/blue/query/26613652 HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:20 +0000] "GET /firethorn/adql/table/26612173 HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:20 +0000] "GET /firethorn/blue/query/26613652 HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:14:45:23 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:23 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            ....
            195.194.121.66 - - [04/Feb/2019:14:45:38 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 503 299 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:38 +0000] "POST /firethorn/adql/resource/54/queries/create HTTP/1.1" 503 299 "-" "Python-urllib/3.4"

        Block of normal behaviour, multiple requests within a few seconds.

            195.194.121.66 - - [04/Feb/2019:13:05:09 +0000] .... 200
            ....
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] .... 200

        External '/availability' request sits between good and bad requests.

            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/resource/56 HTTP/1.1" 200 617 "-" "Python-urllib/3.4"
            178.79.157.93  - - [04/Feb/2019:14:00:01 +0000] "GET /osa/availability HTTP/1.1" 503 299 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "POST /firethorn/blue/query/26613652 HTTP/1.1" 502 438 "-" "Python-urllib/3.4"

        Question - why the 1hr difference between the log entries ?

            https://serverfault.com/questions/661116/why-does-my-apache-access-log-timestamp-sometimes-go-backwards
            "The time in the log message indicates when the request was received. However each request is only logged once processing it has completed."

        Implication of that is crazy - it means many of the '13:05:17' requests took ~1hr to complete "

        Interesting transition, 200, 200, 502, 502, 503, 503

            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/schema/548      HTTP/1.1"  200 783 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/resource/56     HTTP/1.1"  200 617 "-" "Python-urllib/3.4"
            ----
            178.79.157.93  - - [04/Feb/2019:14:00:01 +0000] "GET /osa/availability               HTTP/1.1"  503 299 "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
            ----
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "POST /firethorn/blue/query/26613652 HTTP/1.1"  502 438 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:13:05:17 +0000] "GET /firethorn/adql/table/26612173  HTTP/1.1"  502 437 "-" "Python-urllib/3.4"
            ----
            195.194.121.66 - - [04/Feb/2019:14:45:18 +0000] "GET /firethorn/adql/table/26612173  HTTP/1.1"  503 299 "-" "Python-urllib/3.4"
            195.194.121.66 - - [04/Feb/2019:14:45:17 +0000] "GET /firethorn/blue/query/26613652  HTTP/1.1"  503 299 "-" "Python-urllib/3.4"

        Edited to show time and status ..

            13:05:17 status 200
            13:05:17 status 200
            ----
            14:00:01 status 503
            ----
            13:05:17 status 502
            13:05:17 status 502
            ----
            14:45:18 status 503
            14:45:17 status 503

        Reading between the lines ... and constructing a story.

            Timestamp indicates when the request starts.
            Position  indicates when the request completes.

            13:05:17 status 200 - GET  /adql/schema/548      PASS OK
            13:05:17 status 200 - GET  /adql/resource/56     PASS OK
            ---- failure happens here ?
            14:00:01 status 503 - GET  /availability at 14:00 => immediate 503 response ?
            ----
            13:05:17 status 502 - POST /firethorn/blue/query/26613652 at 13:05:17 => 502 response after 14:00:01 (+1hr)
            13:05:17 status 502 - GET  /firethorn/adql/table/26612173 at 13:05:17 => 502 response after 14:00:01 (+1hr)
            ----
            14:45:18 status 503 - GET  /firethorn/adql/table/26612173 at 14:45:18 => 503 response
            14:45:17 status 503 - GET  firethorn/blue/query/26613652  at 14:45:17 => 503 response (>+1sec)

        Suggest adding %D to the Apache logging ?

            https://serverfault.com/a/734235
            ".. enable the request duration logging, %D .."

            https://serverfault.com/a/661150
            ".. useful to include %D in the LogFormat .. can see how many microseconds each request took."

        We don't know which set of tests this Apache log fragment applies to.
        Need to add more metadata to the logs and the tests.

        Add timestamp to the firethorn-py test logs so we can match them up with Apache logs.
        Add fingerprint requests to the firethorn-py tests so we can match them up with Apache logs.

            http://.../firethorn/logsync/$(uuid)

        Response from firethorn would be immediate 404, so we get a common entry in all the logs.

        We could add something that checks the logs for specific error messages and sends us an email asap.

    ---- ----
    gedit ${notepath}/20190212-Firethorn-utils-Healthchecker-run.txt

        Command to invoke the Healthchecker.
        Sends an email with warnings if the target service is low on memory or disk space.

            /usr/bin/python3 -c "import firethorn_utils.system_checker as system_checker;system_checker.main()" -ft=http://localhost:8081/firethorn


    ---- ----
    gedit ${notepath}/20190304-OSA-TAP-Debug.txt

        ## Issue:
        ## tap.roe.ac.u/osa not responding..

        ssh access still ok.

        firethorn log fragment

            tail -f -n 1000 logs/firethorn-debug.log)

            2019-03-04 15:24:31,488 DEBUG [callback-interface-9] [HttpRequestDebug] Request properties
            ....
            2019-03-04 15:25:31,988 DEBUG [callback-interface-8] [HttpRequestDebug] ----

        Shows system info requests on callback port (8081) and FireThornTaskScheduler runing garbage collector

        Last entry in the firethorn log is [2019-03-04 15:25:31].
        Although we don't know what [now] is ..

        Apache log - total I think (command line asked for 1000, but only got 7)

            tail -f -n 1000 /var/log/httpd/error_log

            [Wed Feb 13 19:21:03.434148 2019] [core:notice] [pid 1:tid 140063511570688] AH00094: Command line: 'httpd -D FOREGROUND'
            [Wed Feb 13 20:17:03.518490 2019] [mpm_event:notice] [pid 1:tid 140063511570688] AH00493: SIGUSR1 received.  Doing graceful restart
            [Wed Feb 13 20:17:03.555844 2019] [lbmethod_heartbeat:notice] [pid 1:tid 140063511570688] AH02282: No slotmem from mod_heartmonitor
            [Wed Feb 13 20:17:03.556624 2019] [http2:warn] [pid 1:tid 140063511570688] AH02951: mod_ssl does not seem to be enabled
            [Wed Feb 13 20:17:03.557467 2019] [mpm_event:notice] [pid 1:tid 140063511570688] AH00489: Apache/2.4.34 (Fedora) configured -- resuming normal operations
            [Wed Feb 13 20:17:03.557495 2019] [core:notice] [pid 1:tid 140063511570688] AH00094: Command line: 'httpd -D FOREGROUND'
            [Sun Mar 03 00:15:07.405452 2019] [mpm_event:error] [pid 1:tid 140063511570688] AH00484: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting

        From this we know service was started [Wed Feb 13 19:21:03] and something happened around [Sun Mar 03 00:15:07].

        Proxy error log

            tail -f -n 10000 /var/log/httpd/tap.roe.ac.uk-error.log

            Error messages are in pairs (original editing didn't match that)

            [Fri Mar 01 00:36:41.161899 2019] [proxy_http:error] [pid 1217:tid 140062624831232] (70007)The timeout specified has expired: [client 133.40.215.109:56982] AH01102: error reading status line from remote server araybwyn:8080
            [Fri Mar 01 00:36:41.161996 2019] [proxy:error] [pid 1217:tid 140062624831232] [client 133.40.215.109:56982] AH00898: Error reading from remote server returned by /osa/sync
            ----
            [Sun Mar 03 00:52:56.134648 2019] [proxy_http:error] [pid 330:tid 140062524151552] (70007)The timeout specified has expired: [client 133.40.215.109:39175] AH01102: error reading status line from remote server araybwyn:8080
            [Sun Mar 03 00:52:56.134739 2019] [proxy:error] [pid 330:tid 140062524151552] [client 133.40.215.109:39175] AH00898: Error reading from remote server returned by /osa/sync
            ....
            [Sun Mar 03 00:52:56.135275 2019] [proxy_http:error] [pid 953:tid 140062532544256] (70007)The timeout specified has expired: [client 133.40.215.109:39179] AH01102: error reading status line from remote server araybwyn:8080
            [Sun Mar 03 00:52:56.135315 2019] [proxy:error] [pid 953:tid 140062532544256] [client 133.40.215.109:39179] AH00898: Error reading from remote server returned by /osa/sync
            ----
            [Sun Mar 03 00:52:56.135698 2019] [proxy_http:error] [pid 330:tid 140062490580736] (70007)The timeout specified has expired: [client 133.40.215.109:39173] AH01102: error reading status line from remote server araybwyn:8080
            [Sun Mar 03 00:52:56.135748 2019] [proxy:error] [pid 330:tid 140062490580736] [client 133.40.215.109:39173] AH00898: Error reading from remote server returned by /osa/sync
            ----
            [Sun Mar 03 00:52:56.135968 2019] [proxy_http:error] [pid 1283:tid 140062683547392] (70007)The timeout specified has expired: [client 133.40.215.109:39177] AH01102: error reading status line from remote server araybwyn:8080
            [Sun Mar 03 00:52:56.136027 2019] [proxy:error] [pid 1283:tid 140062683547392] [client 133.40.215.109:39177] AH00898: Error reading from remote server returned by /osa/sync
            ----
            [Sun Mar 03 00:52:56.136243 2019] [proxy_http:error] [pid 330:tid 140062465402624] (70007)The timeout specified has expired: [client 133.40.215.109:39181] AH01102: error reading status line from remote server araybwyn:8080
            [Sun Mar 03 00:52:56.136278 2019] [proxy:error] [pid 330:tid 140062465402624] [client 133.40.215.109:39181] AH00898: Error reading from remote server returned by /osa/sync
            ....
            ....
            [Mon Mar 04 12:40:03.347248 2019] [proxy_http:error] [pid 542:tid 140062691940096] (70007)The timeout specified has expired: [client 94.66.222.128:25738] AH01102: error reading status line from remote server araybwyn:8080
            [Mon Mar 04 12:40:03.347304 2019] [proxy:error] [pid 542:tid 140062691940096] [client 94.66.222.128:25738] AH00898: Error reading from remote server returned by /firethorn/system/info
            ----
            [Mon Mar 04 13:07:21.755999 2019] [proxy_http:error] [pid 953:tid 140062532544256] (70007)The timeout specified has expired: [client 145.238.193.18:25063] AH01102: error reading status line from remote server araybwyn:8080
            [Mon Mar 04 13:07:21.756079 2019] [proxy:error] [pid 953:tid 140062532544256] [client 145.238.193.18:25063] AH00898: Error reading from remote server returned by /osa/sync
            ----
            [Mon Mar 04 13:40:01.241575 2019] [proxy_http:error] [pid 755:tid 140061861455616] (70007)The timeout specified has expired: [client 178.79.157.93:43840] AH01102: error reading status line from remote server araybwyn:8080
            [Mon Mar 04 13:40:01.241656 2019] [proxy:error] [pid 755:tid 140061861455616] [client 178.79.157.93:43840] AH00898: Error reading from remote server returned by /osa/availability
            ----
            [Mon Mar 04 14:40:01.839986 2019] [proxy_http:error] [pid 755:tid 140062834550528] (70007)The timeout specified has expired: [client 178.79.157.93:43844] AH01102: error reading status line from remote server araybwyn:8080
            [Mon Mar 04 14:40:01.840082 2019] [proxy:error] [pid 755:tid 140062834550528] [client 178.79.157.93:43844] AH00898: Error reading from remote server returned by /osa/availability
            ----
            [Mon Mar 04 14:47:21.927419 2019] [proxy_http:error] [pid 953:tid 140061618198272] (70007)The timeout specified has expired: [client 145.238.193.18:25063] AH01102: error reading status line from remote server araybwyn:8080
            [Mon Mar 04 14:47:21.927514 2019] [proxy:error] [pid 953:tid 140061618198272] [client 145.238.193.18:25063] AH00898: Error reading from remote server returned by /osa/sync

        Early stages [Fri Mar 01 00:36:41] we see a failed request from a client in Japan,  [133.40.215.109], to the sync endpoint.

            [/osa/sync] from [133.40.215.109]

        Middle stage [Sun Mar 03 00:52:56] to [Sun Mar 03 00:52:56] we see repeated requests from the same client in Japan, [133.40.215.109], to the same URL.
        Very tight loop, less than a second between the requests, but error says timeout has expired ?

            [/osa/sync] from [133.40.215.109]

        Later stages [Mon Mar 04 12:40:03] to [Mon Mar 04 14:47:21] we see a mix of clients.
        Separate requests, order of 30-4 minutes between them.
        All with the same error message.

            [/firethorn/system/info]    from [94.66.222.128]        Athens
            [/osa/sync]                 from [145.238.193.18]       Paris
            [/osa/availability]         from [178.79.157.93]        Linode - data.metagrid.co.uk

        I think key part of the error messages is '(70007)The timeout specified has expired' and not 'AH01102: error reading status line from remote server'.

        Proxy access log

            "Looking through /var/log/httpd/tap.roe.ac.uk-access.log"

            ....
            ....
            145.238.193.18 - - [02/Mar/2019:23:14:36 +0000] "GET /firethorn/tap/54/async/30320305 HTTP/1.1" 200 1120 "-" "STILTS/3.1-4 Java/1.7.0_161"
            145.238.193.18 - - [02/Mar/2019:23:14:37 +0000] "GET /firethorn/tap/54/async/30320305 HTTP/1.1" 200 1120 "-" "STILTS/3.1-4 Java/1.7.0_161"
            ....
            ....
            145.238.193.18 - - [02/Mar/2019:23:14:55 +0000] "GET /firethorn/tap/54/async/30320305 HTTP/1.1" 200 1120 "-" "STILTS/3.1-4 Java/1.7.0_161"
            145.238.193.18 - - [02/Mar/2019:23:14:56 +0000] "GET /firethorn/tap/54/async/30320305 HTTP/1.1" 200 1120 "-" "STILTS/3.1-4 Java/1.7.0_161"
            ----
            133.40.215.109 - - [02/Mar/2019:23:12:56 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR9.FileGroupMap&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            133.40.215.109 - - [02/Mar/2019:23:12:56 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR9.DBColumns&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            ....
            ....
            133.40.215.109 - - [02/Mar/2019:23:14:56 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR7.SpecLineNames&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            133.40.215.109 - - [02/Mar/2019:23:14:56 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR7.SiteDBs&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            ----
            145.238.193.18 - - [02/Mar/2019:23:14:57 +0000] "GET /firethorn/tap/54/async/30320305 HTTP/1.1" 502 441 "-" "STILTS/3.1-4 Java/1.7.0_161"
            ----
            133.40.215.109 - - [02/Mar/2019:23:14:58 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR7.UberCal&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            133.40.215.109 - - [02/Mar/2019:23:14:58 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR7.SpecZWarning&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            133.40.215.109 - - [02/Mar/2019:23:14:59 +0000] "GET /osa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR7.SpecLineIndex&LANG=ADQL HTTP/1.1" 502 395 "-" "Java/1.8.0_152"
            ----
            133.40.215.109 - - [03/Mar/2019:00:54:59 +0000] "GET /ssa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR5.TilingInfo&LANG=ADQL HTTP/1.1" 404 206 "-" "Java/1.8.0_152"
            133.40.215.109 - - [03/Mar/2019:00:54:59 +0000] "GET /ssa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR5.QsoBunch&LANG=ADQL HTTP/1.1" 404 206 "-" "Java/1.8.0_152"
            ....
            ....
            ....
            ....
            133.40.215.109 - - [03/Mar/2019:00:55:12 +0000] "GET /ssa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR1.DBObjects&LANG=ADQL HTTP/1.1" 404 206 "-" "Java/1.8.0_152"
            133.40.215.109 - - [03/Mar/2019:00:55:12 +0000] "GET /ssa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR1.Sector&LANG=ADQL HTTP/1.1" 404 206 "-" "Java/1.8.0_152"

            ---- ----

            [02/Mar/2019:23:14:36] to [02/Mar/2019:23:14:56]
            Stilts client from Paris, [145.238.193.18].
            Polling async query status, /firethorn/tap/54/async/30320305, around 1/2 sec between requests.

            [02/Mar/2019:23:12:56] to [02/Mar/2019:23:14:59]
            20 requests from a Java client (not Stilts) in Japan [133.40.215.109] all within 2 minutes.
            Validator queries for BestDR9 and BestDR7, all get a 502 error response.

                SELECT TOP 1 * from BestDR9.FileGroupMap
                ....
                SELECT TOP 1 * from BestDR7.SpecLineIndex

            In the middle of that section the Stilts client from Paris also gets a 502 response, and is not heard from again.

                145.238.193.18 - - [02/Mar/2019:23:14:57 +0000] "GET /firethorn/tap/54/async/30320305 HTTP/1.1" 502 441 "-" "STILTS/3.1-4 Java/1.7.0_161"

            Gap from [02/Mar/2019:23:14:59 +0000] to [03/Mar/2019:00:54:59 +0000].
            No requests logged for 40 minutes.

            [03/Mar/2019:00:54:59] to [03/Mar/2019:00:55:12]
            Final seection, 322 validator requests within 1 minute.
            All from the same Java client (not Stilts) in Japan [133.40.215.109].
            Validator queries for BestDR1 to BestDR9, all get a 404 error response.

                133.40.215.109 - - [03/Mar/2019:00:54:59 +0000] "GET /ssa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR5.TilingInfo&LANG=ADQL HTTP/1.1" 404 206 "-" "Java/1.8.0_152"
                ....
                133.40.215.109 - - [03/Mar/2019:00:55:12 +0000] "GET /ssa/sync?REQUEST=doQuery&QUERY=SELECT+TOP+1+*+from+BestDR1.Sector&LANG=ADQL HTTP/1.1" 404 206 "-" "Java/1.8.0_152"

            IF the timestamp in the Apache log files reflect the time when the request arrived, then this suggests the Japanese client sends ~100 validation requests in parallel.
            Replacing them with new requests when they return a 404 error code.


            At some point we change from 502 errors to 404 errors.
            Is that a change in firethorn behaviour, or are the tables just not there ?

            ---- ----

            2019-02-13 20:17:03 Apache proxy started

            2019-03-01 00:36:41 single failed request (timeout)

            2019-03-02 23:14:36 STILTS polling job status (2 per sec) (permanent RUNNING?)
            2019-03-02 23:14:56 --

            2019-03-02 23:12:56 first 502 errors reported (out of sequence by 2 minutes)

            2019-03-02 23:14:59 No requests logged for 40 minutes.
            2019-03-02 00:54:59

            2019-03-03 00:15:07 Apache warns about MaxRequestWorkers limit

            2019-03-03 00:52:56 large block of /sync requests fail (timeout) all within a couple of seconds

            2019-03-03 00:54:59 block of 322 /sync requests return 404
            2019-03-03 00:55:12

            2019-03-04 12:40:03 mix of failed requests, 30-40 minutes between them

            2019-03-04 14:47:21 last request via proxy

            2019-03-04 15:25:31 Firethorn still handling system info requests.


    ---- ----
    gedit ${notepath}/20190309-Testing-Firethorn.txt

        # This is run locally, with a tunneled connection to Gworewia which is running an httpd proxy
        # Firethorn Chain is running on Cadelicia on trop01
        # ssh -L '*:8081:Gworewia:80' Stevedore@Gworewia


        Trying to reproduce hung query by triggering ChaosMonkey targets.
        Queries either COMPLETE or FAILED, unable to reproduce the hang.

    ---- ----
    gedit ${notepath}/20190311-Failing-Query-FIRETHORN-logs.txt

    ---- ----
    gedit ${notepath}/20190311-Failing-Query-OGSADAI-logs.txt

    ---- ----
    gedit ${notepath}/20190311-Firethorn-Testing.txt

        # 11 March 2019 - Testing for Non-completing queries in Firethorn
        # This is run locally, with a tunneled connection to Gworewia which is running an httpd proxy
        # Firethorn Chain is running on Cadelicia on trop01
        # ssh -L '*:8081:Gworewia:80' Stevedore@Gworewia

            Testing [BestDR1.SpecObjAll]
                ValueError: invalid literal for int() with base 10

            ....
            ....

            Testing [BestDR1.FileGroupMap]
                Rowcount:5
                Table query completed after 2.302009105682373 seconds

            Testing [BestDR1.ELRedShift]

        ## Test Hangs Here

        ## Grab Firethorn and OGSA-DAI logs from last two queries and compare
        ## Logs in separate notes files

        ## Leaving this test running will continue to poll /PHASE of that job every second.
        ## I can start another test which will run a few more queries successfully before hanging again

    ---- ----

TODO
20190311-Working-Query-FIRETHORN-logs.txt
20190311-Working-Query-OGSADAI-logs.txt
20190312-Failing-Query-VVVDR4-FIRETHORN-logs.txt
20190312-Failing-Query-VVVDR4-OGSADAI-logs.txt
20190312-Working-Query-VVVDR4-FIRETHORN-logs.txt
20190312-Working-Query-VVVDR4-OGSADAI-logs.txt
20190315-VM-Deploy-with-build.txt
20190316-Firethorn-Testing-Froeseth.txt
20190316-Firethorn-Testing-Sync.txt
20190318-Testing-Firethorn.txt
20190319-FAIL-Query-OGSADAI.txt
20190319-Working-Query-OGSADAI.txt


---------------------------------------------------------------

    Missing callnback.
        Exception handling in OGSA-DAI means callback is never triggered.
        Query a table that is in the metadata but is missing from the database.
        So far, ChaosMonkey fails to reproduce this.

    Incomplete jobs.
        Race condition in TAP async and instant callback means COMPLETED status gets overwitten by RUNNING.
        Adding a 1ms delay to the OGSA-DAI processing reduces the probability of this.
        Fix is to refactor the TAP async handler.

    Threadlock
        Too many active threads locks up Tomcat.
        Coordinate the query timeout limits to avoid this.


